### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by dapurv5** [raghakot/keras-resnet#7]
I am seeing the following error when trying to train the model for 3000 (224*224) images. I am running it against theano on a g2.2x instance. Does keras copy all training examples to GPU (which is 4gb) before starting to train or it just copies one batch at a time. I was able to run the smaller network for cifar10 without any problems. Anything I am missing?

```
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/theano/gof -fvisibility=hidden -o /home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpHQHx4h/af8288e23d4f9216c7a523f6c00e6cf5.so /home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpHQHx4h/mod.cpp -L/usr/lib -lpython2.7
ERROR (theano.gof.cmodule): [Errno 12] Cannot allocate memory
Traceback (most recent call last):
...

 File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 75, in output_subprocess_Popen
    p = subprocess_Popen(command, **params)
File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 36, in subprocess_Popen
   proc = subprocess.Popen(command, startupinfo=startupinfo, **params)
File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
   self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by raghakot** [comment]
Try setting a smaller batch size. Keras tries to load a;; batch_size number of images into the gpu memory.

**Comment by raghakot** [comment]
Here is an example of using a generator (typically coupled with augmentation to prevent overfitting).
https://github.com/raghakot/ultrasound-nerve-segmentation/blob/master/train.py#L73

Feel free to copy source and modify as needed.
